name: HealthBot Chat Workflow

on:
  push:
    branches:
      - main
  # optional: allow manual run
  workflow_dispatch:

jobs:
  call_openai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call OpenAI API
        run: |
          curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {
                  "role": "system",
                  "content": "You are HealthBot, a friendly AI assistant providing safe health awareness info. You do not give prescriptions."
                },
                {
                  "role": "user",
                  "content": "Hello from GitHub Actions!"
                }
              ]
            }'
